#!/bin/bash

function gen_180_days {
    python << EOF
import datetime
d = datetime.date.today()
for i in range(720):
    print (d - datetime.timedelta(days=i)).isoformat().replace("-","-")
EOF
}

gen_180_days | while read line; do
    year=$(echo "$line" |  awk -F- '{print $1}')
    year_c=$[$year-1911]
    month=$(echo "$line" |  awk -F- '{print $2}')
    day=$(echo "$line" |  awk -F- '{print $3}')

if [[ "$1" == "waitsu" ]]; then
    wget --post-data="download=csv&qdate=$year_c%2F$month%2F$day&sorting=by_issue" http://www.twse.com.tw/ch/trading/fund/TWT38U/TWT38U.php -O "$year""$month""$day".csv
elif [[ "$1" == "tsuyinshan" ]]; then
    wget --post-data="download=csv&qdate=$year_c%2F$month%2F$day&sorting=by_issue" http://www.twse.com.tw/ch/trading/fund/TWT43U/TWT43U.php -O "$year""$month""$day".csv
elif [[ "$1" == "toshin" ]]; then
    wget --post-data="download=csv&qdate=$year_c%2F$month%2F$day&sorting=by_issue" http://www.twse.com.tw/ch/trading/fund/TWT44U/TWT44U.php -O "$year""$month""$day".csv

fi

if [[ "$1" == "waitsu" ]]; then
    sed -i 's/*/\ /' "$year""$month""$day".csv
elif [[ "$1" == "tsuyinshan" ]]; then
    sed -i 's/=*//' "$year""$month""$day".csv
elif [[ "$1" == "toshin" ]]; then
    sed -i 's/*/\ /' "$year""$month""$day".csv

fi

iconv -f big5 -t utf-8  "$year""$month""$day".csv -o "$year""$month""$day".csv

sync
done
