#!/bin/bash

days=$(date --date="yesterday" +"%Y%m%d")
wget -O - "www.twse.com.tw/ch/trading/fund/TWT38U/TWT38U_print.php?edition=ch&filename=genpage/A"$days".dat&type=csv" > $days.csv
sleep 0.2
sed -i 's/^[^0-9]*//' "$days.csv"
iconv -f big5 -t utf-8 "$days.csv" -o "$days.csv"
mv /root/"$days.csv" /root/stock_ui/data/
 
