#!/bin/bash

function gen_180_days {
    python << EOF
import datetime
d = datetime.date.today()
for i in range(720):
    print (d - datetime.timedelta(days=i)).isoformat().replace("-","")
EOF
}

gen_180_days | while read line; do
wget -O - "www.twse.com.tw/ch/trading/fund/TWT38U/TWT38U_print.php?edition=ch&filename=genpage/A"$line".dat&type=csv" > $line.csv
sleep 0.2
sed -i 's/^[^0-9]*//' "$line.csv"
iconv -f big5 -t utf-8 "$line.csv" -o "$line.csv"
done
